//
//  BazelDep.swift
//
//
//  Created by Yume on 2022/7/5.
//

// MARK: - BazelDep

/// Released versions of the Bazel modules Bazelize emits into `MODULE.bazel`.
///
/// Generated by the `repo-enum` package plugin; see `RepoSources.yml`.
enum BazelDep { }
