{
  "target_definitions": [
    {
      "name": "Pods",
      "abstract": true,
      "user_project_path": "ABCDEF.xcodeproj",
      "children": [
        {
          "name": "ABCDEF",
          "uses_frameworks": {
            "linkage": "dynamic",
            "packaging": "framework"
          },
          "configuration_pod_whitelist": {
            "Debug": [
              "Peek"
            ]
          },
          "dependencies": [
            "Peek",
            {
              "AFNetworking": [
                "~> 4.0"
              ]
            },
            "Moya/RxSwift",
            "Moya/Combine",
            {
              "DataCompression": [
                {
                  "git": "https://github.com/mw99/DataCompression"
                }
              ]
            },
            {
              "XLPagerTabStrip": [
                {
                  "git": "https://github.com/xmartlabs/XLPagerTabStrip",
                  "branch": "master"
                }
              ]
            },
            {
              "SVProgressHUD": [
                {
                  "git": "https://github.com/SVProgressHUD/SVProgressHUD",
                  "tag": "2.2.5"
                }
              ]
            },
            {
              "TLPhotoPicker": [
                {
                  "git": "https://github.com/tilltue/TLPhotoPicker",
                  "commit": "0d0cbbd2d20ed5fd36e5f4052209f5e2d9aaa8b7"
                }
              ]
            }
          ],
          "use_modular_headers": {
            "for_pods": [
              "AFNetworking"
            ]
          }
        }
      ]
    }
  ]
}
