# Generated using Bazelize 0.0.5 - https://github.com/XCodeBazelize/Bazelize

load("@build_bazel_rules_apple//apple:apple.bzl", "apple_dynamic_xcframework_import")

apple_dynamic_xcframework_import(
    name = "SVProgressHUD",
    xcframework_imports = glob([
        "SVProgressHUD.xcframework/**",
    ]),
    visibility = [
        "//visibility:public",
    ],
)