//
//  PluginSPM2.swift
//
//
//  Created by Yume on 2023/1/31.
//

import Foundation
import PathKit

// MARK: - PluginSPM

/// The manifests SwiftPM resolves the project's packages from.
///
/// The rules behind those packages are generated by `SwiftPM.Generator`; this
/// plugin only writes what SwiftPM itself reads, and tells each target which
/// product labels to depend on.
final class PluginSwiftPM: PluginBuiltin {
    let remotes: [RemotePackage]
    let locals: [LocalPackage]
    private var projectPath: Path?

    func loadPackageNames(projPath: Path) async throws {
        projectPath = projPath
    }

    override init(_ kit: Kit) {
        remotes = kit.project.packages.remote
        locals = kit.project.packages.local
        super.init(kit)
    }

    /// The package a product belongs to and the product's own name. `nil` when the
    /// product cannot be traced back to a package.
    func facadeProduct(_ product: PackageProductDependency) -> FacadeProduct? {
        remoteProduct(product) ?? localProduct(product)
    }

    /// NIO, from a remote package.
    private func remoteProduct(_ product: PackageProductDependency) -> FacadeProduct? {
        let name = product.productName
        guard let url = product.package ?? remoteURL(forProduct: name) else { return nil }

        return .init(package: Self.packageDirectoryName(url: url), product: name)
    }

    /// Xcode can reference a package product without linking it back to the package.
    /// The repository named after the product is the only sound guess, and it covers
    /// the common one-product-per-package layout.
    private func remoteURL(forProduct product: String) -> String? {
        remotes.compactMap(\.repositoryURL).first { url in
            Self.repositoryModuleName(url: url).caseInsensitiveCompare(product) == .orderedSame
        }
    }

    private func localProduct(_ product: PackageProductDependency) -> FacadeProduct? {
        let product = product.productName

        let directory: String
        if let packagePath = kit.project.localPackagePathByProduct[product] {
            directory = Path(packagePath).lastComponent
        } else if let declared = kit.project.localPackageDirectoryByProduct[product] {
            directory = declared
        } else {
            return nil
        }

        return .init(package: directory, product: product)
    }

    override var target: [String : [String]]? {
        kit.project.targets.map { target -> (String, [String]) in
            let labels = target.dependencies.packageProducts
                .compactMap(facadeProduct)
                .map { product in
                    facadeLabel(package: product.package, product: product.product)
                }
            return (target.name, Set(labels).sorted())
        }.toDictionary()
    }

    private var package: PluginBuiltin.Custom {
        let spms = remotes.compactMap { remote -> String? in
            guard let url = remote.repositoryURL else { return nil }
            if let version = remote.version {
                switch version {
                case .upToNextMajorVersion(let version):
                    return #"        .package(url: "\#(url)", from: "\#(version)"),"#
                case .upToNextMinorVersion(let version):
                    return #"        .package(url: "\#(url)", .upToNextMinor(from: "\#(version)")),"#
                case .exact(let version):
                    /// An exact version names one commit, and upstream deleting or
                    /// re-tagging it makes the manifest unresolvable. Xcode's own pin
                    /// records the revision, so use it when it is available.
                    if let revision = pinnedRevision(url: url) {
                        return #"        .package(url: "\#(url)", revision: "\#(revision)"), // \#(version)"#
                    }
                    return #"        .package(url: "\#(url)", exact: "\#(version)"),"#
                case .branch(let branch):
                    return #"        .package(url: "\#(url)", branch: "\#(branch)"),"#
                case .revision(let revision):
                    return #"        .package(url: "\#(url)", revision: "\#(revision)"),"#
                case .range(let from, let to):
                    return #"        .package(url: "\#(url)", "\#(from)"..."\#(to)"),"#
                }
            }
            return #"        .package(url: "\#(url)", from: "0.0.1"),"#
        } +
            locals.map { local in
                #"        .package(path: "\#(localPackagePath(local))"),"#
            }
        let deps = spms.joined(separator: "\n").indent(2)
        return .init(
            path: "Package.swift",
            content: """
            // swift-tools-version: 6.0
            import PackageDescription

            let package = Package(
                name: "MySwiftPackage",
                dependencies: [
            \(deps)
                ]
            )
            """)
    }

    /// Seeds Xcode's own pins so the first `swift package resolve` keeps the versions
    /// the project builds against instead of floating every package to its newest
    /// release. Never overwrites an existing file: after the first run the resolved
    /// graph belongs to SwiftPM and Bazel.
    private var packageResolved: PluginBuiltin.Custom? {
        guard !remotes.isEmpty else { return nil }
        guard let projectPath else { return nil }
        guard !(kit.outputRoot + "Package.resolved").exists else { return nil }

        let resolved = projectPath + "project.xcworkspace/xcshareddata/swiftpm/Package.resolved"
        guard let content = try? String(contentsOfFile: resolved.string, encoding: .utf8) else { return nil }

        return .init(path: "Package.resolved", content: content)
    }

    /// Revisions Xcode already resolved, keyed by package identity.
    private lazy var pinnedRevisions: [String: String] = {
        guard let projectPath else { return [:] }

        let resolved = projectPath + "project.xcworkspace/xcshareddata/swiftpm/Package.resolved"
        guard
            let data = try? Data(contentsOf: URL(fileURLWithPath: resolved.string)),
            let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
            let pins = json["pins"] as? [[String: Any]]
        else {
            return [:]
        }

        return pins.reduce(into: [String: String]()) { result, pin in
            guard
                let identity = pin["identity"] as? String,
                let state = pin["state"] as? [String: Any],
                let revision = state["revision"] as? String
            else {
                return
            }
            result[identity] = revision
        }
    }()

    private func pinnedRevision(url: String) -> String? {
        pinnedRevisions[Self.repositoryModuleName(url: url).lowercased()]
    }

    /// The workspace's own way to run its build tool plugins.
    override func build(_ builder: CodeBuilder) {
        guard hasPackages else { return }

        builder.load(loadableRule: Rules.Shell.sh_binary)
        builder.call(
            Rules.Shell.Call.sh_binary(
                name: "plugins",
                srcs: ["plugins.sh"]))
    }

    override var custom: [PluginBuiltin.Custom]? {
        guard hasPackages else { return nil }

        return [package, packageResolved].compactMap { $0 } + [ignore, plugins]
    }

    /// `bazel run //:plugins`: what brings the files a build tool plugin writes
    /// up to date, without generating the workspace again.
    ///
    /// A plugin decides what it writes, so changing the plugin changes those
    /// files while nothing else about the project moves — and the rules glob the
    /// directory rather than name the files, so they need no regenerating. This
    /// is the workspace's own way to run them, the way `bazel mod tidy` is the
    /// workspace's way to fix its module file.
    private var plugins: PluginBuiltin.Custom {
        let arguments = ["--output", "."] + locals.flatMap { local in
            ["--local", (kit.project.workspaceRoot + local.relativePath).absolute().string.quoted]
        }

        return .init(
            path: "plugins.sh",
            content: """
            #!/bin/bash
            # Runs this workspace's build tool plugins, writing what they generate
            # back into `Packages/*/Generated/*Plugin`.
            set -euo pipefail
            cd "${BUILD_WORKSPACE_DIRECTORY:-$(dirname "$0")}"
            exec bazelize plugins \(arguments.joined(separator: " "))

            """)
    }

    /// SwiftPM's working directory is not part of the Bazel workspace: a checkout
    /// can carry `BUILD` files of its own, and Bazel would try to load them.
    private var ignore: PluginBuiltin.Custom {
        .init(path: ".bazelignore", content: ".build\n")
    }

    private var hasPackages: Bool {
        !remotes.isEmpty || !locals.isEmpty
    }

    /// Where a local package is, relative to the generated manifest.
    ///
    /// Both ends are resolved first: an output directory reached through a symlink
    /// would otherwise climb out of the link's real parent, and SwiftPM resolves
    /// the path it is given against that real one.
    private func localPackagePath(_ local: LocalPackage) -> String {
        let source = (kit.project.workspaceRoot + local.relativePath).absolute()
        let base = kit.outputRoot.absolute()
        return Self.relativePath(
            from: Self.resolved(base.string),
            to: Self.resolved(source.string))
    }

    /// The real path, symlinks and all.
    ///
    /// Not `resolvingSymlinksInPath()`: that one drops a leading `/private`, which
    /// is exactly the prefix a temporary directory resolves to.
    private static func resolved(_ path: String) -> String {
        guard let resolved = realpath(path, nil) else { return path }
        defer { free(resolved) }
        return String(cString: resolved)
    }

    /// The directory a package's products are exposed under, named the way a human
    /// refers to the package.
    static func packageDirectoryName(url: String) -> String {
        repositoryModuleName(url: url)
    }

    private static func repositoryModuleName(url: String) -> String {
        let component = Path(url).lastComponent
        if component.hasSuffix(".git") {
            return String(component.dropLast(4))
        }
        return component
    }

    private static func relativePath(from base: String, to target: String) -> String {
        let baseURL = URL(fileURLWithPath: base, isDirectory: true).standardized
        let targetURL = URL(fileURLWithPath: target, isDirectory: true).standardized

        let baseComponents = baseURL.pathComponents
        let targetComponents = targetURL.pathComponents

        var commonCount = 0
        while
            commonCount < min(baseComponents.count, targetComponents.count),
            baseComponents[commonCount] == targetComponents[commonCount]
        {
            commonCount += 1
        }

        let upward = Array(repeating: "..", count: baseComponents.count - commonCount)
        let downward = Array(targetComponents.dropFirst(commonCount))
        return (upward + downward).joined(separator: "/")
    }
}
