import Foundation
import PathKit

extension Bazel {
    /// tools/asset_symbols.bzl
    ///
    /// `actool` is the only thing that knows how an asset catalog becomes Swift
    /// members, and no ruleset wraps it for that: the symbols a target compiles
    /// are generated by a rule the workspace carries itself.
    ///
    /// It is a rule rather than a `genrule` because the action is an Apple one.
    /// `apple_support.run` puts the selected Xcode in the action's environment
    /// and in its key, so symbols generated by one Xcode are not reused by
    /// another, and the platform comes from the configuration the target is
    /// built in rather than from whatever the project said when it was read.
    struct AssetSymbols: BazelFile {
        // MARK: Lifecycle

        init(_ root: Path) {
            path = root + "tools" + "asset_symbols.bzl"
        }

        // MARK: Internal

        let path: Path

        let code = """
        \"\"\"The asset catalog symbols a target compiles.\"\"\"

        load("@apple_support//lib:apple_support.bzl", "apple_support")

        _PLATFORMS = {
            "ios": ("iphoneos", "iphonesimulator"),
            "macos": ("macosx", "macosx"),
            "tvos": ("appletvos", "appletvsimulator"),
            "visionos": ("xros", "xrsimulator"),
            "watchos": ("watchos", "watchsimulator"),
        }

        def _platform(ctx):
            \"\"\"The `--platform` actool compiles for, from the configuration.

            A build that carries no Apple platform constraint — the rule asked for
            on its own, outside the bundle that transitions to its platform — falls
            back to what the project was read as.
            \"\"\"
            target_os = apple_support.target_os_from_rule_ctx(
                ctx,
                fail_on_missing_constraint = False,
            )
            if not target_os or target_os not in _PLATFORMS:
                return ctx.attr.platform

            environment = apple_support.target_environment_from_rule_ctx(
                ctx,
                fail_on_missing_constraint = False,
            )
            device, simulator = _PLATFORMS[target_os]
            return simulator if environment == "simulator" else device

        def _catalogs(files):
            \"\"\"The catalog directories the given files belong to, in order.\"\"\"
            catalogs = []
            for file in files:
                index = file.path.find(".xcassets/")
                if index == -1:
                    continue
                catalog = file.path[:index] + ".xcassets"
                if catalog not in catalogs:
                    catalogs.append(catalog)
            return catalogs

        def _asset_symbols_impl(ctx):
            catalogs = _catalogs(ctx.files.catalogs)
            if not catalogs:
                fail("no asset catalog among the files given to " + str(ctx.label))

            symbols = ctx.actions.declare_file("GeneratedAssetSymbols.swift")

            # `actool` emits symbols only while compiling, and the compiled catalog
            # is the bundle rule's to produce: this one is declared so the action is
            # hermetic, and nothing reads it.
            compiled = ctx.actions.declare_directory(ctx.label.name + ".compiled")

            arguments = ctx.actions.args()
            arguments.add_all(catalogs)
            arguments.add("--compile", compiled.path)
            arguments.add("--platform", _platform(ctx))
            arguments.add("--minimum-deployment-target", ctx.attr.minimum_os_version)
            arguments.add("--bundle-identifier", ctx.attr.bundle_id)
            arguments.add("--output-format", "human-readable-text")
            arguments.add("--generate-swift-asset-symbol-extensions", "YES")
            arguments.add("--generate-swift-asset-symbols", symbols.path)

            # `actool` reports what it compiled on stdout, which Bazel would print
            # for every target that has a catalog. The shell is here for that
            # redirect alone: the arguments are still passed as arguments, so a
            # catalog whose name has a space in it stays one argument.
            apple_support.run_shell(
                actions = ctx.actions,
                xcode_config = ctx.attr._xcode_config[apple_common.XcodeVersionConfig],
                apple_fragment = ctx.fragments.apple,
                command = '/usr/bin/xcrun actool "$@" > /dev/null',
                arguments = [arguments],
                inputs = ctx.files.catalogs,
                outputs = [symbols, compiled],
                mnemonic = "AssetSymbols",
                progress_message = "Generating asset symbols for %{label}",
            )

            return [DefaultInfo(files = depset([symbols]))]

        asset_symbols = rule(
            implementation = _asset_symbols_impl,
            attrs = {
                "bundle_id": attr.string(
                    mandatory = True,
                    doc = "The identifier actool keys the generated symbols with.",
                ),
                "catalogs": attr.label_list(
                    allow_files = True,
                    mandatory = True,
                    doc = "Every file of every asset catalog the symbols come from.",
                ),
                "minimum_os_version": attr.string(
                    mandatory = True,
                    doc = "The deployment target the generated availability is written against.",
                ),
                "platform": attr.string(
                    mandatory = True,
                    doc = "The platform to compile for when the configuration names none.",
                ),
            } | apple_support.action_required_attrs() | apple_support.platform_constraint_attrs(),
            fragments = ["apple"],
            doc = "Generates the Swift asset symbols a target's sources reference.",
        )

        """
    }
}
