//
//  SwiftPM+Language.swift
//
//
//  The localizations a workspace's packages ship, as something a build picks.
//

import Foundation
@preconcurrency import PathKit
import Util

extension SwiftPM.Generator {
    /// One localization, and the packages that ship it.
    struct Localization {
        /// `en`, `ja`, `Base` — the name of the `.lproj` directory, without it.
        let code: String
        /// The packages whose resources are in that language.
        let packages: [String]
        /// The packages that call it their default: what a resource declared
        /// without a language of its own is filed under.
        let defaultOf: [String]

        /// `lang.<code>`, the name a `--config` goes by.
        var config: String {
            "lang.\(code)"
        }
    }

    /// Every localization every package in the workspace ships.
    ///
    /// A `.lproj` directory is what makes a resource localized — SwiftPM needs
    /// nothing declared for it — so the directories are what is read, plus each
    /// package's `defaultLocalization`, which it may declare without shipping
    /// anything under that name yet.
    var localizations: [Localization] {
        var packagesByCode: [String: [String]] = [:]
        var defaultsByCode: [String: [String]] = [:]

        for package in workspace.packages.sorted(by: { $0.directory < $1.directory }) {
            var codes: Set<String> = []

            for target in package.manifest.targets {
                guard let directory = sourceDirectory(of: target, in: package) else { continue }

                for file in Self.walk(directory) {
                    for component in file.components where component.hasSuffix(".lproj") {
                        codes.insert(String(component.dropLast(".lproj".count)))
                    }
                }
            }

            if let fallback = package.manifest.defaultLocalization {
                codes.insert(fallback)
                defaultsByCode[fallback, default: []].append(package.directory)
            }

            for code in codes {
                packagesByCode[code, default: []].append(package.directory)
            }
        }

        return packagesByCode.keys.sorted().map { code in
            Localization(
                code: code,
                packages: (packagesByCode[code] ?? []).sorted(),
                defaultOf: (defaultsByCode[code] ?? []).sorted())
        }
    }

    /// `--config=lang.<code>` for every localization the workspace's packages
    /// ship.
    ///
    /// A build that names none bundles them all, which is what SwiftPM does.
    /// Naming one is how an app ships a single language; `Base` comes along
    /// whatever is asked for, because it is what a missing localization falls
    /// back to.
    ///
    /// The file is always written, because a `.bazelrc` that imports a file
    /// that is not there does not load.
    func writeLanguageConfigs() throws {
        let localizations = self.localizations
        var lines = [
            "# Generated by Bazelize: one --config per localization the packages of",
            "# this workspace ship. A build that names none bundles every one of",
            "# them, which is what SwiftPM does; `Base` is kept whatever is asked",
            "# for.",
        ]

        if localizations.isEmpty {
            lines.append("#")
            lines.append("# No package in this workspace ships a localization.")
        }

        for localization in localizations {
            let shipped = localization.packages.joined(separator: ", ")
            let fallback = localization.defaultOf.isEmpty
                ? ""
                : ", the default of \(localization.defaultOf.joined(separator: ", "))"

            lines.append("")
            lines.append("# \(localization.code): shipped by \(shipped)\(fallback)")
            lines.append(
                "build:\(localization.config) "
                    + "--@build_bazel_rules_apple//apple/build_settings:locales_to_include="
                    + localization.code)
        }

        try (output + "languages.bazelrc").write(lines.joined(separator: "\n") + "\n")
    }
}
