name: Swift

on: 
  push:
    branches: 
      - master
    paths:
      - 'Source/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'
  pull_request:
    paths:
      - 'Source/**'
      - 'Tests/**'
      - '.github/workflows/**'
      - 'Package.swift'

concurrency: 
  group: ci
  cancel-in-progress: true

jobs:
  build:

    # https://github.com/actions/virtual-environments
    # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md
    runs-on: macos-12

    strategy:
      matrix:
        xcode: 
        - "13.3.1"
        - "13.3"
        - "13.2.1"

    steps:
    - uses: actions/checkout@v2

    - name: Check Cocoapod Path
      run: which pod

    - name: Update Cocoapod Repo
      run: pod repo update

    - name: Xcode Select ${{ matrix.xcode }}
      # You may pin to the exact commit or the version.
      # uses: devbotsxyz/xcode-select@05f94658217eb8575f0aabd3b95e702a47995d21
      uses: devbotsxyz/xcode-select@v1.1.0
      with:
        # Version to use (like '11.7', '12' or simply 'latest')
        version: ${{ matrix.xcode }} # optional, default is latest
        # Whether to select a beta release or not. Beta releases may not always be available.
        beta: false # optional, default is false

    - name: Get swift version
      run: swift --version # Swift 5.3.3

    - name: SPM Cache ${{ matrix.xcode }}
      uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-${{ matrix.xcode }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.xcode }}-spm-
      
    - name: Build ${{ matrix.xcode }}
      run: swift build -v
      
    - name: Run tests ${{ matrix.xcode }}
      run: swift test -v 2>&1 | xcpretty
